### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by XShockinFireX** [NL-4-DEVS/Parkour#25]
Can you make it so that you can add multiple reward commands, and add an option to erase checkpoint data every time a player leaves?

**Comment by Driesboy** [comment]
Thats possble

**Comment by Driesboy** [comment]
1/2 done

**Comment by XShockinFireX** [comment]
k

**Comment by Driesboy** [comment]
i am working on 2/2

**Comment by Driesboy** [comment]
oops

**Comment by Driesboy** [comment]
i will finish it today

**Comment by XShockinFireX** [comment]
@Driesboy Cool, thanks!

**Comment by Driesboy** [comment]
not been added 
i think i will add it later
sorry i dont have time to fix this maybe @Sandertv can do this

**Comment by Sandertv** [comment]
The option to erase checkpoint data every time a player leaves?

**Comment by Driesboy** [comment]
yes

**Comment by XShockinFireX** [comment]
Well I've learned how to program in PHP and Java, and make plugins... I'll make a PR to add all suggestions in this issue later.

**Comment by Driesboy** [comment]
thx
