### ISSUE TITLE
Earn Reward doesn't work the config is nothing

### ISSUE THREAD

**Issue by Mike4l6** [NL-4-DEVS/Parkour#27]
Yeaa

**Comment by Driesboy** [comment]
ok i will try to fix this

**Comment by Driesboy** [comment]
i dont have this bug

**Comment by Mike4l6** [comment]
https://github.com/NL-4-DEVS/Parkour/releases 
I downloaded the latest one

**Comment by Mike4l6** [comment]
maybe cause I'm using Genisys

**Comment by Driesboy** [comment]
no
use the source plz
i will update the releases soon

**Comment by Mike4l6** [comment]
I used the source theres still a bug

**Comment by Mike4l6** [comment]
no checkpoints dont even work :/

**Comment by Driesboy** [comment]
i will fix the source soon

**Comment by RocoWayne** [comment]
any news?

**Comment by Driesboy** [comment]
no

**Comment by RocoWayne** [comment]
Works for me now. My friend create a config file with all of this. Checkpoints, rewards, messages, etc

**Comment by Driesboy** [comment]
yes ok i will try to fix this

**Comment by Driesboy** [comment]
please test
