### ISSUE TITLE
Extremely Laggy

### ISSUE THREAD

**Issue by isoz** [NL-4-DEVS/Parkour#28]
This plugin has become extremely laggy that I had to disable it from my servers.
An example of my timings can be found in this screenshot:
http://prnt.sc/bxvhey

It seems that the interaction with the Checkpoint needs to be revised, I'm only using Checkpoints with this plugin, nothing else. (onplayertouch & onplayerinteractevent).

Also maybe setting a way where the user cannot spam the sign might also help.

**Comment by Driesboy** [comment]
This plugin is dead sorry

**Comment by Driesboy** [comment]
Is it fixed in 0.16.0?

**Comment by TheBluePinguin1** [comment]
isoz do synapse works on your server

**Comment by TheBluePinguin1** [comment]
and driesboy tells me that he will fix it soon

**Comment by Driesboy** [comment]
complete

**Comment by isoz** [comment]
whats complete? lol this shit will lag your server to hell.

**Comment by Driesboy** [comment]
i have make it alot faster !

**Comment by Driesboy** [comment]
i cannot make it faster than now or i need to disable block touch

**Comment by isoz** [comment]
that's what causes the lag...

**Comment by isoz** [comment]
find another method...

**Comment by Driesboy** [comment]
do you need it?

**Comment by Driesboy** [comment]
i can make a branch without it

**Comment by isoz** [comment]
No, i can do it myself, but then that's just gonna make the plugin useless

**Comment by Driesboy** [comment]
but i dont go disable tile touch but block touch
