### ISSUE TITLE
I test Parkour but does not create a config folder

### ISSUE THREAD

**Issue by RocoWayne** [NL-4-DEVS/Parkour#29]
I just have installed this plugin on my server but i dont see a config folder. I test the [Checkpoint] signs and nothing.

Y check with /pl if there is any problem with the plugin and appear just ther without problem.

What im doing wrong?

**Comment by Driesboy** [comment]
fixed?

**Comment by RocoWayne** [comment]
Yes, a friend fixed for me

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
how do you fix it ?
